source 'https://rubygems.org'
gem 'pry-debugger', :group => 'development'
gem 'sinatra', '~>1.3.4'
gem 'haml'
gem 'unicorn', :group => 'production'
gem 'omniauth'
gem 'omniauth-google-oauth2'
gem 'activerecord'
gem 'sqlite3'
gem 'sinatra-cometio'
gem 'thin'
gem 'treetop'
