source 'https://rubygems.org'
gem 'sinatra', '~>1.3.4'
gem 'haml'
gem 'omniauth'
gem 'omniauth-google-oauth2'
gem 'activerecord'
gem 'sqlite3', :group => 'development'
gem 'pg', :group => 'production'
gem 'sinatra-cometio'
gem 'thin'
gem 'treetop'
gem 'airbrake', :group => 'production'
gem 'beaneater'
gem 'daemons'
gem 'pg_search'
