- hosts: web
  user: deployer
  tasks:
  - command: "git pull chdir=/home/deployer/student-checklist"
  - command: "bundle install --deployment chdir=/home/deployer/student-checklist"
  - copy: src=../config.yaml dest=/home/deployer/student-checklist/config.yaml
  - command: "sh -c 'RACK_ENV=production bundle exec ruby run_migrations.rb' chdir=/home/deployer/student-checklist"
  - command: sh -c "if [ -e tmp/pids/thin.pid ]; then cat tmp/pids/thin.pid | xargs kill; fi; while [ -e tmp/pids/thin.pid ]; do sleep 1; done" chdir=/home/deployer/student-checklist
  - command: "bundle exec thin start -p 3003 -e production -d chdir=/home/deployer/student-checklist"
