- hosts: web
  user: root
  tasks:
  - command: "/usr/sbin/adduser deployer --disabled-password --gecos '' creates=/home/deployer"
  - command: mkdir /home/deployer/.ssh creates=/home/deployer/.ssh
  - command: chown deployer:deployer /home/deployer/.ssh
  - command: cp /root/.ssh/authorized_keys /home/deployer/.ssh/authorized_keys
  - command: chown deployer:deployer /home/deployer/.ssh/authorized_keys
  - command: chmod 0600 /home/deployer/.ssh/authorized_keys

  - command: apt-get update

  - apt: "pkg=ruby1.9.3"
  - apt: "pkg=nginx"
  - apt: "pkg=git"
  - apt: "pkg=make"
  - apt: "pkg=g++"
  - apt: "pkg=postgresql"
  - apt: "pkg=libpq-dev"
  - apt: "pkg=libsqlite3-dev"
  - apt: "pkg=nodejs" # for coffeescript
  - apt: "pkg=beanstalkd"

  - command: mkdir /var/lib/postgresql/.ssh creates=/var/lib/postgresql/.ssh
  - command: chown postgres:postgres /var/lib/postgresql/.ssh
  - command: cp /root/.ssh/authorized_keys /var/lib/postgresql/.ssh/authorized_keys
  - command: chown postgres:postgres /var/lib/postgresql/.ssh/authorized_keys
  - command: chmod 0600 /var/lib/postgresql/.ssh/authorized_keys

  - command: gem install bundler creates=/usr/local/bin/bundle

  - copy: src=beanstalkd dest=/etc/default/beanstalkd
  - command: service beanstalkd start

- hosts: web
  user: postgres
  tasks:
  - command: sh -c "createuser -S -D -R student_checklist && touch .created_role_for_student_checklist" creates=/var/lib/postgresql/.created_role_for_student_checklist
  - command: "sh -c \"echo alter user student_checklist with password \\\\'student_checklist\\\\' | psql\""
  - command: sh -c "createdb -O student_checklist student_checklist && touch .created_db_for_student_checklist" creates=/var/lib/postgresql/.created_db_for_student_checklist

- hosts: web
  user: deployer
  tasks:
  - command: "git clone https://github.com/danielstutzman/student-checklist creates=/home/deployer/student-checklist"
  - command: "bundle install --deployment chdir=/home/deployer/student-checklist"
  - copy: src=../config.yaml dest=/home/deployer/student-checklist/config.yaml
  - command: "sh -c 'RACK_ENV=production bundle exec ruby run_migrations.rb' chdir=/home/deployer/student-checklist"
  - command: "mkdir -p tmp tmp/sockets tmp/pids log chdir=/home/deployer/student-checklist"
  - command: sh -c "if [ -e tmp/pids/thin.pid ]; then cat tmp/pids/thin.pid | xargs kill; rm tmp/pids/thin.pid; fi" chdir=/home/deployer/student-checklist
  - command: "bundle exec thin start -p 3003 -e production -d chdir=/home/deployer/student-checklist"

  - copy: src=dot-pgpass dest=/home/deployer/.pgpass
  - command: chmod 0600 /home/deployer/.pgpass

- hosts: web
  user: root
  tasks:
  - copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  - command: service nginx restart
